version: "3.2"

networks:
  net_intl:
    ipam:
      config:
        - subnet: 10.2.22.0/24

volumes: 
  data_shared: {}
      
services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Sela_1234
      MYSQL_DATABASE: arus
    ports:
      - "3307:3306"
    volumes:
      - /root/arus.sql:/arus.sql

  laravel-service:
    build:
      args:
        user: broadcomm
        uid: 1000
      context: /var/www/laravel
      dockerfile: Dockerfile
    image: ghcr.io/arus/laravel-service
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - /var/www/laravel:/var/www/
      - /data_shared:/data_shared
      - /data_shared:/var/www/public/data_shared
    networks:
      - net_intl

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:80"
    volumes:
      - /var/www/laravel:/var/www
      - /data_shared:/var/www/public/data_shared
      - ./nginx:/etc/nginx/conf.d
    networks:
      - net_intl
